project:
  type: website

website:
  site-url: "https://www.wasuhdud.org"
  title: "Suh dud"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



